version: '3.0'

services:
  my-mongo-database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: userDB
    image: mongo:latest
    container_name: my-db

  flask-web-app:
    build: .
    container_name: flask-app
    ports:
      - "8081:8081"
    depends_on:
      - my-db
